=== cherrysiyu/plugin/dbutils/target/classes/libo-db.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://libo.com/db" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://libo.com/db">
	
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	
	<xs:annotation>
		<xs:documentation><![CDATA[
	LIBO DB Configuation Schema, version 1.0
	Authors: libo
		]]></xs:documentation>
	</xs:annotation>
	
	<!-- 自定义数据类型：值不能为空 -->
	<xs:simpleType name="d_required">
		<xs:restriction base="xs:string">
			<!-- 处理所有的空白字符 -->
			<xs:whiteSpace value="collapse"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- 自定义数据类型：最小值1 -->
	<xs:simpleType name="min_1">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- 自定义数据类型：最小值0 -->
	<xs:simpleType name="min_0">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	<!-- 根元素 -->
	<xs:element name="datasources">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="0" ref="constants"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="datasource"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="include"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="link-mapping"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- constants定义 -->
	<xs:element name="constants">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="constant">
					<xs:complexType>
						<xs:attribute name="name" type="d_required" use="required"/>
						<xs:attribute name="value" type="d_required" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<!-- datasource定义 -->
	<xs:element name="datasource">
		<xs:complexType>
			<xs:all> 
				<xs:element name="name" type="d_required"/>
				<xs:element name="driver-class" type="d_required"/>
				<xs:element name="driver-url" type="d_required"/>
				<xs:element name="user" type="d_required"/>
				<xs:element name="password" type="xs:string"/>
				
				<xs:element maxOccurs="1" minOccurs="0" name="max-connection-size" type="min_1"/>
				<xs:element maxOccurs="1" minOccurs="0" name="min-connection-size" type="min_1"/>
				<xs:element maxOccurs="1" minOccurs="0" name="init-connection-size" type="min_1"/>
				
				<xs:element maxOccurs="1" minOccurs="0" name="acquire-increment-size" type="min_1"/>
				<xs:element maxOccurs="1" minOccurs="0" name="available-connection-size" type="min_0"/>
				
				<xs:element maxOccurs="1" minOccurs="0" name="max-connection-idletime" type="min_1"/>
				<xs:element maxOccurs="1" minOccurs="0" name="max-connection-lifetime" type="min_1"/>
				
				<xs:element maxOccurs="1" minOccurs="0" name="idle-connection-test-period" type="min_0"/>
				<xs:element maxOccurs="1" minOccurs="0" name="acquire-retry-attempts" type="min_0"/>
				<xs:element maxOccurs="1" minOccurs="0" name="acquire-retry-delay" type="min_0"/>
				
				<xs:element maxOccurs="1" minOccurs="0" name="test-sql" type="xs:string"/>
				<xs:element maxOccurs="1" minOccurs="0" name="test-connection-checkout" type="xs:boolean"/>
				<xs:element maxOccurs="1" minOccurs="0" name="test-connection-checkin" type="xs:boolean"/>
				
				<xs:element maxOccurs="1" minOccurs="0" name="connection-timeout" type="min_0"/>
				<xs:element maxOccurs="1" minOccurs="0" name="load-on-startup" type="xs:boolean"/>
				<xs:element maxOccurs="1" minOccurs="0" name="show-sql" type="xs:boolean"/>
				<xs:element maxOccurs="1" minOccurs="0" name="connection-provider" type="d_required"/>
				
				<xs:element maxOccurs="1" minOccurs="0" name="customize"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- include定义 -->
	<xs:element name="include">
		<xs:complexType>
			<xs:attribute name="datasource" type="d_required" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<!-- link-mapping定义 -->
	<xs:element name="link-mapping">
		<xs:complexType>
			<xs:attribute name="name" type="d_required" use="required"/>
			<xs:attribute name="linkto" type="d_required" use="required"/>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== cherrysiyu/plugin/dbutils/src/main/resource/all-configure-demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- The datasource file is only an example file -->
<datasources xmlns="http://libo.com/db"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://libo.com/db/libo-db.xsd">
	
	<constants>
		<constant name="max-connection-size" value="100"/>
	 	<constant name="min-connection-size" value="5"/>
	 	<constant name="init-connection-size" value="10"/>
	 	<constant name="available-connection-size" value="2"/>
	 	<constant name="acquire-increment-size" value="10"/>
	 	
	 	<constant name="max-connection-idletime" value="3600"/>
	 	<constant name="max-connection-lifetime" value="14400"/>
	 	<constant name="idle-connection-test-period" value="3600"/>
	 	<constant name="connection-timeout" value="5"/>
	 	 
		<constant name="acquire-retry-attempts" value="10"/>
		<constant name="acquire-retry-delay" value="1000"/>
		
		<constant name="test-sql" value="SELECT 1"/>
		<constant name="test-connection-checkout" value="true"/>
		<constant name="test-connection-checkin" value="true"/>
	 	
	 	<constant name="load-on-startup" value="true"/>
	 	<constant name="show-sql" value="false"/>
		
		<constant name="connection-provider" value="com.libo.db.connection.c3p0.C3P0ConnectionProvider"/>
		<!-- 
		<constant name="connection-provider" value="com.libo.db.connection.bonecp.BoneCPConnectionProvider"/>
		 -->
	</constants>
	
	<datasource>
		<name>my</name>
		<driver-class>com.mysql.jdbc.Driver</driver-class>
		<driver-url>jdbc:mysql://10.0.125.15:3306/crm_v3</driver-url>
		<user>root</user>
		<password>libo2011</password>
		
		<max-connection-size>100</max-connection-size>
		<min-connection-size>5</min-connection-size>
		<init-connection-size>10</init-connection-size>
		<available-connection-size>2</available-connection-size>
		<acquire-increment-size>10</acquire-increment-size>
		
		<max-connection-idletime>3600</max-connection-idletime>
		<max-connection-lifetime>14400</max-connection-lifetime>
		<idle-connection-test-period>3600</idle-connection-test-period>
		<connection-timeout>5</connection-timeout>
		
		<acquire-retry-attempts>10</acquire-retry-attempts>
		<acquire-retry-delay>1000</acquire-retry-delay>
		
		<test-sql>SELECT 1</test-sql>
		<test-connection-checkin>false</test-connection-checkin>
		<test-connection-checkout>false</test-connection-checkout>
		
		<load-on-startup>true</load-on-startup>
		<show-sql>false</show-sql>
		
		<connection-provider>com.libo.db.connection.c3p0.C3P0ConnectionProvider</connection-provider>
		<!-- 
		<connection-provider>com.libo.db.connection.bonecp.BoneCPConnectionProvider</connection-provider>
		 -->
		
		<customize>
			<yourname>your value</yourname>
			<!-- 0 å°å¤ä¸ª
			<xxx>...</xxx>
			 -->
		</customize>
		
	</datasource>
	
	<!-- 0 å° å¤ä¸ª
	<datasource>
		<name></name>
		<driver-class></driver-class>
		<driver-url></driver-url>
		<user></user>
		<password></password>
		......			
	</datasource>
	 -->
	
	<include datasource="/yourdatasource.xml"/>
	
	<!-- 0 å°å¤ä¸ª
	<include datasource="your datasource xml path"/>
	 -->
	 
	<link-mapping name="you" linkto="my"/>
	
	<!-- 0 å°å¤ä¸ª
	<link-mapping name="..." linkto="..."/>
	 -->
	
</datasources>
